name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Test
        run: pnpm test
      - name: Build the project
        run: pnpm run build
